# Generated by Django 5.0.6 on 2024-06-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_no', models.CharField(max_length=200, null=True)),
                ('gc_dt', models.CharField(max_length=200, null=True)),
                ('invoice_dt', models.CharField(max_length=200, null=True)),
                ('consignor_name', models.CharField(max_length=200, null=True)),
                ('consignee_name', models.CharField(max_length=200, null=True)),
                ('vechile_no', models.CharField(max_length=200, null=True)),
                ('from_addr', models.CharField(max_length=200, null=True)),
                ('to_addr', models.CharField(max_length=200, null=True)),
                ('invoice_no', models.CharField(max_length=200, null=True)),
                ('invoice_amount', models.CharField(max_length=200, null=True)),
                ('note', models.CharField(max_length=200, null=True)),
                ('articles', models.CharField(max_length=200, null=True)),
                ('topay', models.CharField(max_length=200, null=True)),
                ('paid', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
