# Generated by Django 5.0.6 on 2024-06-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_party_gc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consignor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consignor_name", models.CharField(max_length=200, null=True)),
                ("consignor_phno", models.CharField(max_length=200, null=True)),
                ("consignor_addr", models.CharField(max_length=200, null=True)),
                ("consignor_gst", models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
