# Generated by Django 5.2.6 on 2026-01-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_consignee'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Consignee',
        ),
        migrations.DeleteModel(
            name='Consignor',
        ),
        migrations.DeleteModel(
            name='Insert',
        ),
        migrations.DeleteModel(
            name='Party_gc',
        ),
    ]
