# Generated by Django 6.0 on 2026-01-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_designation_alter_department_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile_no", models.CharField(blank=True, max_length=15, null=True)),
                ("full_name", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("present_address", models.TextField(blank=True, null=True)),
                ("permanent_address", models.TextField(blank=True, null=True)),
                ("joining_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "employee_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("check_in", models.TimeField(blank=True, null=True)),
                ("check_out", models.TimeField(blank=True, null=True)),
                (
                    "department_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "designation_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("salary_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "salary_amount",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "full_day_absence_fine",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "half_day_absence_fine",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "yearly_leave_limit",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
