# Generated by Django 4.2.27 on 2026-01-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_employee"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceMaster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.IntegerField()),
                ("full_name", models.CharField(max_length=255)),
                ("check_in", models.TimeField()),
                ("check_out", models.TimeField(blank=True, null=True)),
                (
                    "worked_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("worked_day", models.CharField(blank=True, max_length=20, null=True)),
                ("att_date", models.DateField()),
                ("photo", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.CharField(max_length=255)),
                ("longitude", models.CharField(max_length=255)),
                ("out_photo", models.CharField(blank=True, max_length=255, null=True)),
                ("out_lati", models.CharField(max_length=250)),
                ("out_long", models.CharField(max_length=250)),
                ("attendance_status", models.CharField(max_length=250)),
                ("is_paid", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "attendance_master",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AttendanceReq",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(max_length=50)),
                ("reg_date", models.DateField()),
                ("full_name", models.CharField(max_length=100)),
                ("reason", models.TextField()),
                ("attachment", models.CharField(max_length=250)),
                ("check_in", models.TimeField()),
                ("check_out", models.TimeField()),
                ("approval_status", models.CharField(max_length=250)),
                ("status", models.CharField(max_length=250)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "attendance_req",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DeptMaster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "db_table": "dept_master",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DesigMaster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dept_name", models.CharField(max_length=255)),
                ("desig_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "desig_master",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmpItemMaster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(max_length=255)),
                ("item_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "item_amt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "item_amt_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("item_type", models.CharField(blank=True, max_length=50, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "emp_item_master",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmpMaster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.CharField(max_length=255, unique=True)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("contact", models.CharField(blank=True, max_length=20, null=True)),
                ("present_addr", models.TextField(blank=True, null=True)),
                ("perm_addr", models.TextField(blank=True, null=True)),
                ("join_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("emp_type", models.CharField(blank=True, max_length=50, null=True)),
                ("check_in", models.TimeField(blank=True, null=True)),
                ("check_out", models.TimeField(blank=True, null=True)),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("dept", models.CharField(blank=True, max_length=255, null=True)),
                ("desig", models.CharField(blank=True, max_length=255, null=True)),
                ("salary_type", models.CharField(blank=True, max_length=50, null=True)),
                ("salary_amt", models.CharField(max_length=255)),
                (
                    "full_abs_fine",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "half_abd_fine",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("yearly_leaves", models.IntegerField(blank=True, null=True)),
                ("bank", models.CharField(blank=True, max_length=255, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("account_name", models.CharField(max_length=255)),
                ("account_no", models.CharField(blank=True, max_length=50, null=True)),
                ("ifsc_code", models.CharField(blank=True, max_length=20, null=True)),
                ("entried_by", models.CharField(blank=True, max_length=255, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("total_yearly_leaves", models.CharField(max_length=250)),
                ("profile_photo", models.CharField(max_length=250)),
                ("blood_group", models.CharField(max_length=250)),
                ("father_name", models.CharField(max_length=250)),
                ("emergency_contact", models.IntegerField()),
            ],
            options={
                "db_table": "emp_master",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmpTemp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("contact", models.CharField(max_length=15, unique=True)),
                ("email", models.CharField(max_length=150, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("dob", models.DateField()),
                ("gender", models.CharField(max_length=50)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "father_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("religion", models.CharField(blank=True, max_length=50, null=True)),
                ("caste", models.CharField(blank=True, max_length=50, null=True)),
                ("blood_group", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "qualification",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("work", models.CharField(blank=True, max_length=150, null=True)),
                ("experience", models.CharField(blank=True, max_length=20, null=True)),
                ("bank", models.CharField(max_length=200)),
                ("bank_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("ifsc_code", models.CharField(blank=True, max_length=20, null=True)),
                ("status", models.CharField(default="PENDING", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "emp_temp",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_title", models.CharField(max_length=255)),
                ("event_desc", models.TextField()),
                ("event_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "events",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HolidayMaster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("holiday_tital", models.CharField(max_length=255)),
                ("holiday_date", models.DateField()),
            ],
            options={
                "db_table": "holiday_master",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LeaveMaster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_type", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_paid", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "allow_half_day",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "leave_master",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_id", models.IntegerField()),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("leave_type", models.CharField(blank=True, max_length=255, null=True)),
                ("leave_duration", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("leave_status", models.IntegerField(blank=True, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("total_leaves", models.IntegerField(default=0)),
                ("yearly_leaves", models.IntegerField(default=0)),
                ("is_paid", models.IntegerField()),
            ],
            options={
                "db_table": "leave_request",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LogoMaster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_name", models.CharField(max_length=250)),
                ("image_path", models.CharField(max_length=250)),
                ("created_at", models.DateField()),
            ],
            options={
                "db_table": "logo_master",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("email", models.CharField(max_length=200)),
                ("contact", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("cover_img", models.TextField()),
            ],
            options={
                "db_table": "system_settings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TitleMaster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_update", models.CharField(max_length=250)),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "title_master",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("password", models.TextField()),
                ("type", models.IntegerField(default=2)),
                ("contact", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="department",
        ),
        migrations.DeleteModel(
            name="designation",
        ),
        migrations.DeleteModel(
            name="employee",
        ),
    ]
