# Generated by Django 4.2.27 on 2026-03-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_attendancemaster_attendancereq_deptmaster_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeLocationTracking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("emp_id", models.CharField(blank=True, max_length=255, null=True)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("session_date", models.DateField(blank=True, null=True)),
                ("is_checkin_point", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "employee_location_tracking",
                "ordering": ["timestamp"],
            },
        ),
    ]
