# Generated by Django 4.2.27 on 2026-03-26 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_clientvisitor_photo'),
    ]

    operations = [
    ]
