from django.urls import path
from .views import (
    login_api,
    register_api,
    logout_api,
    attendance_checkin,
    attendance_checkout,
    attendance_list,
    attendance_edit_api,
    attendance_req_submit,
    attendance_req_list_api,
    attendance_req_update_api,
    leave_list_create,
    leave_detail,
    leave_status_update_api,
    leave_approve_api,
    leave_reject_api,
    yearly_leave_api,
    leave_types_api,
    admin_profile_api,
    user_profile_api,
    attendance_get,
    employee_list_api,
    employee_list_create_api,
    employee_detail_api,
    emp_temp_list_api,
    emp_temp_approve_api,
    emp_temp_reject_api,
    employee_create_admin_api,
    emp_temp_detail_api,
    upcoming_birthdays_api,
    yearly_leaves,
    location_tracking_api,
    biometric_punch_api,
)
from .push_views import push_broadcast_api, push_register_api

urlpatterns = [
    path("login/", login_api),
    path("register/", register_api),
    path("logout/", logout_api),
    path("attendance/checkin/", attendance_checkin),
    path("attendance/checkout/", attendance_checkout),
    path("attendance/get/", attendance_get),
    path("attendance/list/", attendance_list),
    path("attendance/edit/", attendance_edit_api),
    path("attendance/req/submit/", attendance_req_submit),
    path("attendance/req/list/", attendance_req_list_api),
    path("attendance/req/update/<int:id>/", attendance_req_update_api),
    path("leave/", leave_list_create),
    path("leave/<int:id>/", leave_detail),
    path("leave/<int:id>/status/", leave_status_update_api),
    path("leave/<int:id>/approve/", leave_approve_api),
    path("leave/<int:id>/reject/", leave_reject_api),
    path("yearly-leave/", yearly_leave_api),
    path("leave-types/", leave_types_api),
    path("profile/admin/", admin_profile_api),
    path("profile/user/", user_profile_api),
    path("employee/", employee_list_create_api),
    path("employee/list/", employee_list_api),
    path("employee/create-admin/", employee_create_admin_api),
    # path("employee/by-mobile/", get_employee_by_mobile_api),
    path("employee/<str:emp_id>/", employee_detail_api),
    path("emp_temp/list/", emp_temp_list_api),
    path("emp_temp/<int:id>/", emp_temp_detail_api),
    path("emp_temp/approve/<int:id>/", emp_temp_approve_api),
    path("emp_temp/reject/<int:id>/", emp_temp_reject_api),
    path("emp_birthday/", upcoming_birthdays_api),
    path("yearly-leaves/", yearly_leaves),
    # Accept both with and without trailing slash (helps mobile clients avoid 301 redirects on POST)
    path("location", location_tracking_api),
    path("location/", location_tracking_api),
    path("biometric/punch/", biometric_punch_api),
    path("biometric/punch", biometric_punch_api),
    path("push/register/", push_register_api),
    path("push/broadcast/", push_broadcast_api),
]
